name: Upload to Test PyPi

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    environment:
      name: pypi-publishing
      url: https://test.pypi.org/p/HOPP
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - name: Build package
      run: |
        python -m pip install --upgrade pip
        pip install setuptools build wheel twine
        python -m build
        twine check --strict dist/*
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        verbose: True
        repository-url: https://test.pypi.org/legacy/

