blank_issues_enabled: false
contact_links:
  - name: Usage question
    url: https://github.com/NREL/turbine-models/discussions
    about: Have any questions about using turbine-models? Post in Discussions to engage with the NREL team and turbine-models community.
